-- =============================================
-- DDL Script for Coffee Quality Database
-- Oracle SQL Developer
-- =============================================

-------------------------
-- DROP EXISTING TABLES
-------------------------

ALTER TABLE COFFEE_QUALITY DROP CONSTRAINT COFFEE_SAMPLE_COLOR;
ALTER TABLE COFFEE_QUALITY DROP CONSTRAINT COFFEE_SAMPLE_COUNTRY;
ALTER TABLE COFFEE_QUALITY DROP CONSTRAINT COFFEE_SAMPLE_VARIETY;
ALTER TABLE COUNTRY DROP CONSTRAINT COUNTRY_CONTINENT;
ALTER TABLE COFFEE_QUALITY DROP CONSTRAINT PROCESSING_METHOD;
ALTER TABLE VARIETY DROP CONSTRAINT VARIETY_SPECIES;

DROP TABLE COFFEE_QUALITY;
DROP TABLE COLOR;
DROP TABLE CONTINENT;
DROP TABLE COUNTRY;
DROP TABLE PROCESSING_METHOD;
DROP TABLE SPECIES;
DROP TABLE VARIETY;

-------------------------
-- CREATE TABLES
-------------------------

CREATE TABLE COFFEE_QUALITY (
    REC_ID NUMBER(10) NOT NULL,
    COUNTRY_ID INTEGER,
    HARVEST_YEAR INTEGER,
    EXPIRATION DATE NOT NULL,
    VARIETY_ID INTEGER,
    COLOR_ID INTEGER,
    PROCESSING_METHOD_ID INTEGER,
    AROMA NUMBER(38,10) NOT NULL,
    FLAVOR NUMBER(38,10) NOT NULL,
    AFTERTASTE NUMBER(38,10) NOT NULL,
    ACIDITY NUMBER(38,10) NOT NULL,
    BODY NUMBER(38,10) NOT NULL,
    BALANCE NUMBER(38,10) NOT NULL,
    UNIFORMITY NUMBER(38,10) NOT NULL,
    CLEAN_CUP NUMBER(38,10) NOT NULL,
    SWEETNESS NUMBER(38,10) NOT NULL,
    MOISTURE NUMBER(38,10) NOT NULL,
    QUAKERS INTEGER NOT NULL,
    CATEGORY_ONE_DEFECTS INTEGER NOT NULL,
    CATEGORY_TWO_DEFECTS INTEGER NOT NULL,
    CONSTRAINT COFFEE_QUALITY_PK PRIMARY KEY (REC_ID)
);

CREATE TABLE COLOR (
    COLOR_ID INTEGER NOT NULL,
    COLOR_NAME VARCHAR2(255),
    CONSTRAINT COLOR_PK PRIMARY KEY (COLOR_ID)
);

CREATE TABLE CONTINENT (
    CONTINENT_ID INTEGER NOT NULL,
    CONTINENT_NAME VARCHAR2(255) NOT NULL,
    CONSTRAINT CONTINENT_PK PRIMARY KEY (CONTINENT_ID)
);

CREATE TABLE COUNTRY (
    COUNTRY_ID INTEGER NOT NULL,
    COUNTRY_NAME VARCHAR2(255) NOT NULL,
    CONTINENT_ID INTEGER NOT NULL,
    CONSTRAINT COUNTRY_PK PRIMARY KEY (COUNTRY_ID)
);

CREATE TABLE PROCESSING_METHOD (
    PROCESSING_METHOD_ID INTEGER NOT NULL,
    PROCESSING_METHOD_NAME VARCHAR2(255),
    CONSTRAINT PROCESSING_METHOD_PK PRIMARY KEY (PROCESSING_METHOD_ID)
);

CREATE TABLE SPECIES (
    SPECIES_ID INTEGER NOT NULL,
    SPECIES_NAME VARCHAR2(255) NOT NULL,
    CONSTRAINT SPECIES_PK PRIMARY KEY (SPECIES_ID)
);

CREATE TABLE VARIETY (
    VARIETY_ID INTEGER NOT NULL,
    VARIETY_NAME VARCHAR2(255),
    SPECIES_ID INTEGER NOT NULL,
    CONSTRAINT VARIETY_PK PRIMARY KEY (VARIETY_ID)
);

-------------------------
-- ADD FOREIGN KEYS
-------------------------

ALTER TABLE COFFEE_QUALITY
ADD CONSTRAINT COFFEE_SAMPLE_COLOR
FOREIGN KEY (COLOR_ID)
REFERENCES COLOR (COLOR_ID);

ALTER TABLE COFFEE_QUALITY
ADD CONSTRAINT COFFEE_SAMPLE_COUNTRY
FOREIGN KEY (COUNTRY_ID)
REFERENCES COUNTRY (COUNTRY_ID);

ALTER TABLE COFFEE_QUALITY
ADD CONSTRAINT COFFEE_SAMPLE_VARIETY
FOREIGN KEY (VARIETY_ID)
REFERENCES VARIETY (VARIETY_ID);

ALTER TABLE COUNTRY
ADD CONSTRAINT COUNTRY_CONTINENT
FOREIGN KEY (CONTINENT_ID)
REFERENCES CONTINENT (CONTINENT_ID);

ALTER TABLE COFFEE_QUALITY
ADD CONSTRAINT PROCESSING_METHOD
FOREIGN KEY (PROCESSING_METHOD_ID)
REFERENCES PROCESSING_METHOD (PROCESSING_METHOD_ID);

ALTER TABLE VARIETY
ADD CONSTRAINT VARIETY_SPECIES
FOREIGN KEY (SPECIES_ID)
REFERENCES SPECIES (SPECIES_ID);
