-- =============================================
-- DML Ingestion Script for Coffee Quality Database
-- =============================================

-------------------------
-- INSERT CONTINENTS
-------------------------

INSERT INTO CONTINENT (CONTINENT_ID, CONTINENT_NAME)
SELECT ROW_NUMBER() OVER (ORDER BY CONTINENT_OF_ORIGIN),
       CONTINENT_OF_ORIGIN
FROM (
    SELECT DISTINCT CONTINENT_OF_ORIGIN
    FROM hc848.DATA_COFFEE_QUALITY
    WHERE CONTINENT_OF_ORIGIN IS NOT NULL
);

-------------------------
-- INSERT COUNTRIES
-------------------------

INSERT INTO COUNTRY (COUNTRY_ID, COUNTRY_NAME, CONTINENT_ID)
SELECT ROW_NUMBER() OVER (ORDER BY COUNTRY_OF_ORIGIN),
       src.COUNTRY_OF_ORIGIN,
       c.CONTINENT_ID
FROM (
    SELECT DISTINCT COUNTRY_OF_ORIGIN, CONTINENT_OF_ORIGIN
    FROM hc848.DATA_COFFEE_QUALITY
    WHERE COUNTRY_OF_ORIGIN IS NOT NULL
) src
JOIN CONTINENT c
  ON c.CONTINENT_NAME = src.CONTINENT_OF_ORIGIN;

-------------------------
-- INSERT SPECIES
-------------------------

INSERT INTO SPECIES (SPECIES_ID, SPECIES_NAME)
SELECT ROW_NUMBER() OVER (ORDER BY SPECIES),
       SPECIES
FROM (
    SELECT DISTINCT SPECIES
    FROM hc848.DATA_COFFEE_QUALITY
    WHERE SPECIES IS NOT NULL
);

-------------------------
-- INSERT VARIETY
-------------------------

INSERT INTO VARIETY (VARIETY_ID, VARIETY_NAME, SPECIES_ID)
SELECT ROW_NUMBER() OVER (ORDER BY VARIETY, SPECIES),
       src.VARIETY,
       s.SPECIES_ID
FROM (
    SELECT DISTINCT VARIETY, SPECIES
    FROM hc848.DATA_COFFEE_QUALITY
    WHERE VARIETY IS NOT NULL
) src
JOIN SPECIES s
  ON s.SPECIES_NAME = src.SPECIES;

-------------------------
-- INSERT COLORS
-------------------------

INSERT INTO COLOR (COLOR_ID, COLOR_NAME)
SELECT ROW_NUMBER() OVER (ORDER BY COLOR),
       COLOR
FROM (
    SELECT DISTINCT COLOR
    FROM hc848.DATA_COFFEE_QUALITY
    WHERE COLOR IS NOT NULL
);

-------------------------
-- INSERT PROCESSING METHODS
-------------------------

INSERT INTO PROCESSING_METHOD (PROCESSING_METHOD_ID, PROCESSING_METHOD_NAME)
SELECT ROW_NUMBER() OVER (ORDER BY PROCESSING_METHOD),
       PROCESSING_METHOD
FROM (
    SELECT DISTINCT PROCESSING_METHOD
    FROM hc848.DATA_COFFEE_QUALITY
    WHERE PROCESSING_METHOD IS NOT NULL
);

-------------------------
-- INSERT COFFEE_QUALITY FACT DATA
-------------------------

INSERT INTO COFFEE_QUALITY (
    REC_ID, COUNTRY_ID, HARVEST_YEAR, EXPIRATION,
    VARIETY_ID, COLOR_ID, PROCESSING_METHOD_ID,
    AROMA, FLAVOR, AFTERTASTE, ACIDITY, BODY, BALANCE,
    UNIFORMITY, CLEAN_CUP, SWEETNESS, MOISTURE,
    QUAKERS, CATEGORY_ONE_DEFECTS, CATEGORY_TWO_DEFECTS
)
SELECT dq.REC_ID,
       ctry.COUNTRY_ID,
       dq.HARVEST_YEAR,
       dq.EXPIRATION,
       v.VARIETY_ID,
       col.COLOR_ID,
       pm.PROCESSING_METHOD_ID,
       dq.AROMA,
       dq.FLAVOR,
       dq.AFTERTASTE,
       dq.ACIDITY,
       dq.BODY,
       dq.BALANCE,
       dq.UNIFORMITY,
       dq.CLEAN_CUP,
       dq.SWEETNESS,
       dq.MOISTURE,
       dq.QUAKERS,
       dq.CATEGORY_ONE_DEFECTS,
       dq.CATEGORY_TWO_DEFECTS
FROM hc848.DATA_COFFEE_QUALITY dq
LEFT JOIN COUNTRY ctry
       ON ctry.COUNTRY_NAME = dq.COUNTRY_OF_ORIGIN
LEFT JOIN COLOR col
       ON col.COLOR_NAME = dq.COLOR
LEFT JOIN PROCESSING_METHOD pm
       ON pm.PROCESSING_METHOD_NAME = dq.PROCESSING_METHOD
LEFT JOIN SPECIES s
       ON s.SPECIES_NAME = dq.SPECIES
LEFT JOIN VARIETY v
       ON v.VARIETY_NAME = dq.VARIETY
      AND v.SPECIES_ID = s.SPECIES_ID;
